{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "c985f004",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-12-28 16:11:39.762 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:39.764 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.040 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run c:\\Users\\kalya\\OneDrive\\Desktop\\project\\.venv\\Lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n",
      "2025-12-28 16:11:40.040 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.040 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.040 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.549 Thread 'Thread-3': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.551 Thread 'Thread-3': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.552 Thread 'Thread-3': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.570 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.572 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.573 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.573 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.573 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.574 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.574 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.574 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.574 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.575 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.575 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.577 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.577 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.577 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.577 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.579 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.579 Session state does not function when running a script without `streamlit run`\n",
      "2025-12-28 16:11:40.579 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.580 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.580 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.580 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.580 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.580 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.582 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.582 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.583 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.583 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.584 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.584 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.585 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.585 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.586 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.586 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.586 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.587 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.587 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.587 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.587 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.588 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.588 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.588 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.588 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.589 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.590 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.590 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.591 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.591 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.592 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.592 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.593 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.593 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.594 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.594 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.595 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.595 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.595 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.596 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.596 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.597 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.598 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.598 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.598 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.599 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.599 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.599 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.600 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.600 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.600 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.602 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.602 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.604 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.641 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.642 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.643 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.643 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.644 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.644 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.644 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.644 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-28 16:11:40.646 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import joblib\n",
    "import numpy as np\n",
    "\n",
    "# Page Configuration\n",
    "st.set_page_config(\n",
    "    page_title=\"Fraud Detection System\",\n",
    "    page_icon=\"🛡️\",\n",
    "    layout=\"wide\"\n",
    ")\n",
    "\n",
    "# --- 1. Load Resources ---\n",
    "@st.cache_resource\n",
    "def load_resources():\n",
    "    try:\n",
    "        # Load the model and the feature list saved from the notebook\n",
    "        model = joblib.load(\"fraud_model.pkl\")\n",
    "        feature_names = joblib.load(\"model_features.pkl\")\n",
    "        return model, feature_names\n",
    "    except FileNotFoundError:\n",
    "        st.error(\"Error: Model files not found. Please run the export script in your notebook first.\")\n",
    "        return None, None\n",
    "\n",
    "model, feature_names = load_resources()\n",
    "\n",
    "# --- 2. Application UI ---\n",
    "st.title(\"🛡️ Mobile Transaction Fraud Detection\")\n",
    "st.markdown(\"\"\"\n",
    "This application predicts the likelihood of a transaction being fraudulent based on \n",
    "transactional parameters. It utilizes the machine learning model trained on the Fraud Analysis Dataset.\n",
    "\"\"\")\n",
    "\n",
    "if model:\n",
    "    # Sidebar for inputs\n",
    "    st.sidebar.header(\"📝 Transaction Details\")\n",
    "    \n",
    "    # Input: Step (Time)\n",
    "    step = st.sidebar.number_input(\"Step (Hours)\", min_value=1, max_value=744, value=1, help=\"1 step represents 1 hour of time.\")\n",
    "\n",
    "    # Input: Transaction Type\n",
    "    # Note: Your notebook filters to only CASH_OUT and TRANSFER, so we limit the UI to these.\n",
    "    txn_type = st.sidebar.selectbox(\"Transaction Type\", [\"CASH_OUT\", \"TRANSFER\"])\n",
    "\n",
    "    # Input: Amount\n",
    "    amount = st.sidebar.number_input(\"Amount\", min_value=0.0, value=1000.0, step=10.0)\n",
    "\n",
    "    # Input: Sender Details\n",
    "    st.sidebar.subheader(\"Sender Details\")\n",
    "    oldbalanceOrg = st.sidebar.number_input(\"Sender Old Balance\", min_value=0.0, value=5000.0)\n",
    "    newbalanceOrig = st.sidebar.number_input(\"Sender New Balance\", min_value=0.0, value=4000.0)\n",
    "\n",
    "    # Input: Receiver Details\n",
    "    st.sidebar.subheader(\"Receiver Details\")\n",
    "    oldbalanceDest = st.sidebar.number_input(\"Receiver Old Balance\", min_value=0.0, value=0.0)\n",
    "    newbalanceDest = st.sidebar.number_input(\"Receiver New Balance\", min_value=0.0, value=0.0)\n",
    "\n",
    "    # --- 3. Preprocessing (Matching your Notebook Logic) ---\n",
    "    \n",
    "    # Create the manual flags as done in Cell 94 of your notebook\n",
    "    is_cash_out = 1 if txn_type == \"CASH_OUT\" else 0\n",
    "    is_transfer = 1 if txn_type == \"TRANSFER\" else 0\n",
    "\n",
    "    # Create a dictionary of inputs\n",
    "    input_data = {\n",
    "        'step': step,\n",
    "        'amount': amount,\n",
    "        'oldbalanceOrg': oldbalanceOrg,\n",
    "        'newbalanceOrig': newbalanceOrig,\n",
    "        'oldbalanceDest': oldbalanceDest,\n",
    "        'newbalanceDest': newbalanceDest,\n",
    "        'is_cash_out': is_cash_out,\n",
    "        'is_transfer': is_transfer\n",
    "    }\n",
    "\n",
    "    # Convert to DataFrame\n",
    "    input_df = pd.DataFrame([input_data])\n",
    "\n",
    "    # Ensure columns match exactly what the model was trained on\n",
    "    # This aligns the input_df columns with the saved feature_names order\n",
    "    try:\n",
    "        input_df = input_df[feature_names]\n",
    "    except KeyError as e:\n",
    "        st.error(f\"Feature mismatch: The app is generating features that don't match the model. Missing: {e}\")\n",
    "        st.stop()\n",
    "\n",
    "    # --- 4. Main Display ---\n",
    "    \n",
    "    # Show input summary\n",
    "    st.subheader(\"Transaction Summary\")\n",
    "    st.dataframe(input_df)\n",
    "\n",
    "    # Prediction Button\n",
    "    if st.button(\"Analyze Transaction\", type=\"primary\"):\n",
    "        with st.spinner(\"Analyzing transaction patterns...\"):\n",
    "            \n",
    "            # Make Prediction\n",
    "            prediction = model.predict(input_df)[0]\n",
    "            \n",
    "            # Get Probability (if model supports it)\n",
    "            try:\n",
    "                probability = model.predict_proba(input_df)[0][1]\n",
    "            except:\n",
    "                probability = None\n",
    "\n",
    "            st.divider()\n",
    "\n",
    "            # Display Results\n",
    "            if prediction == 1:\n",
    "                st.error(\"🚨 FRAUD DETECTED\")\n",
    "                st.write(\"This transaction shows patterns consistent with fraudulent activity.\")\n",
    "                if probability is not None:\n",
    "                    st.write(f\"**Confidence Score:** {probability:.2%}\")\n",
    "            else:\n",
    "                st.success(\"✅ TRANSACTION SAFE\")\n",
    "                st.write(\"This transaction appears to be legitimate.\")\n",
    "                if probability is not None:\n",
    "                    st.write(f\"**Fraud Probability:** {probability:.2%}\")\n",
    "\n",
    "else:\n",
    "    st.info(\"Please ensure 'fraud_model.pkl' and 'model_features.pkl' are in the same directory as this app.\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
